import { defineCollection } from "astro:content";
// astro:content still re-exports `z`, but deprecated. `astro/zod` is the same
// zod, reached through a package this repo depends on directly rather than
// through a hoisted transitive one.
import { z } from "astro/zod";
import { glob } from "astro/loaders";
import { docsLoader } from "@astrojs/starlight/loaders";
import { docsSchema } from "@astrojs/starlight/schema";

// Generated by `Scripts/generate_presets.py` from the app repo's preset sidecars
// and committed — the build never reads the app repo. The schema is congruent
// with the sidecar fields it copies, so a sidecar that changes shape fails here
// rather than rendering something wrong.
const presets = defineCollection({
  loader: glob({ pattern: "*.json", base: "./src/content/presets" }),
  schema: z.object({
    slug: z.string(),
    name: z.string(),
    author: z.string(),
    description: z.string(),
    family: z.string(),
    certified: z.boolean(),
    // Milkdrop lineage, on the presets that are ports. None of the three with
    // footage today has one; the field exists for the footage W.3 still owes.
    inspired_by: z
      .object({
        milkdrop_filename: z.string(),
        original_artist: z.string(),
        pack: z.string(),
        source_form: z.string(),
        sha256: z.string().optional(),
      })
      .optional(),
    roster_quote: z.string(),
  }),
});

// ponytail: docs only. Starlight warns about a missing "i18n" collection at build
// time; defining an empty one produces the identical warning, so it is not defined.
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
  presets,
};
